# Allgemeine Prüfungshinweise {#sec-allgemeine-pruefungshinweise}






<!-- ## Allgemeine Prüfungshinweise -->

    

## Grundsätzliches

Die folgenden Hinweise gelten *grundsätzlich*, 
d.h. *soweit nicht anders* in der jeweiligen Prüfung bzw. der jeweiligen Aufgabe angegeben.
Nichtbeachten von Prüfungshinweisen kann zu Punkteabzug oder Nichtbestehen führen.
Lesen Sie sich diese Hinweise im eigenen Interesse sorgfältig durch.
Kenntnis dieser Hinweise wird bei der Begutachtung vorausgesetzt.



Für eine einfachere Kommunikation kontaktieren Sie mich per E-Mail bei Fragen, die nur Sie betreffen. Bei Fragen von allgemeinem Interesse (z.B. "Bis wann müssen wir die Arbeit abgeben?") nutzen Sie bitte (sofern verfügbar) das Kursforum, damit die Kommilitonen auch von dem Austausch profitieren.


Wird eine Prüfungsleistung nicht *frist- und formgerecht eingereicht*, so gilt sie als nicht eingereicht und wird mit "nicht bestanden" bewertet.





## Prüfungsrelevanter Stoff

*Prüfungsrelevanter* Stoff ist alles, was im Unterricht behandelt wurde, sofern es nicht explizit (und schriftlich) als "nicht prüfungsrelevant" oder als "Vertiefung" gekennzeichnet ist.
Insbesondere ist der komplette Inhalt des Skripts und sonstiger vom Dozenten eingestellter Unterlagen prüfungsrelevant (sofern nicht in Teilen anderweitig gekennzeichnet).
Dazu zählen auch Hinweise auf zu lesende Literatur, aber nicht sonstige Literatur im Literaturverzeichnis.
Nicht relevant sind die verlinkte externe Inhalte, d.h. Inhalte von Internetadressen, sofern nicht explizit als prüfungsrelevant gekennzeichnet.
Der prüfungsrelevante Stoff kann von der Lehrkraft bis zum Beginn des Prüfungszeitraums geändert werden.
Die Änderungen am Skript sind, sofern es um ein Skript handelt, das auf Github eingestellt ist, komplett dokumentiert. Der Link zum Quelltext (des Skripts) bzw. den Änderungen daran sind über Github komplett dokumentiert (inkl. Zeitstempel).



## Teilnahmebedingungen

1. Eine *Prüfungsleistung* darf nur *eingereicht* werden, wenn Sie (erfolgreich) zur Prüfung *angemeldet* sind. Eine abgegebene/hochgeladene Arbeit, die nicht erfolgreich angemeldet ist, gilt nicht als erfolgreich eingereicht.
1.  Die Prüfung ist selbständig, also alleine nur durch Sie (Prüfling), *ohne Hilfe Dritter*, zu absolvieren.
2.  Die *Bearbeitungszeiten* der Prüfung sind einzuhalten.
2.  Es dürfen nur die explizit als zulässig gekennzeichneten *Hilfsmittel* verwendet werden.
2.  Die *zulässigen* Hilfsmittel sind: Notizpapier, Stifte, Taschenrechner, Vorlesungsfolien, Skripte, eigene Notizen, Bücher sowie Quellen aus dem Internet.
2.  Die Übernahme von Inhalten Dritter muss also solche gekennzeichnet (*zitiert*) werden. 
2.  Eine wörtliche Übernahme ("*copy-paste*") von Inhalten Dritter (etwa aus einer Quelle aus dem Internet) ist unzulässig.
2.  Bei *technischen Problemen* ist sofort der Prüfer bzw. die Prüferin zu verständigen und das technische Problem zu dokumentieren. Aus der Dokumentation muss der Fehler erkenntlich sein. 
2.  Es ist *untersagt*, die *Prüfung* bzw. Teile daraus (z.B. Prüfungsfragen) zu speichern oder *weiterzugeben.*
2.  Im Übrigen gelten die allgemeinen *Prüfungsregeln*.
2.  Es darf *nicht* mit anderen Personen, insbesondere nicht Prüflingen, *kommuniziert* werden während der Prüfung. Dies gilt auch für den Fall von (vermeintlichen) technischen Problemen. Kontaktieren Sie den Prüfer, wenn Sie meinen, es liege ein technisches Problem vor.


## Wiederholungsprüfungen

1. Wenn Sie bei einer Prüfung durchgefallen sein sollten, so haben Sie grundsätzlich die Möglichkeit, die *Prüfung zu wiederholen*.
2. Denken Sie daran, sich *rechtzeitig* für Prüfungsleistungen *anzumelden*; beachten Sie die Fristen. Beim Zweit- bzw. Drittversuch gelten besondere Regeln und Fristen. Informieren Sie sich umfassend.
3. Die *Termine* für die *Wiederholungsprüfungen* werden stets zusammen/zeitgleich mit denen der regulären Prüfungen bekannt gegeben (in der Regel im Moodlekurs, in dessen Rahmen auch die ursprüngliche Prüfung statt fand). 
3. Relevanter Stoff und formale Bedingungen (wie Prüfungsform) sind *grundsätzlich identisch zur letzten abgehaltenen Prüfung des Moduls* (d.h. sofern nicht anders angegeben). Daher sind Wiederholungsprüfungen vom Anspruch vergleichbar wie die reguläre Klausur. Die Prüfungen sollen möglichst gleich vom Anspruch sein, um Fairness zu gewährleisten.
3. Beachten Sie immer die *Hinweise*, die für die Wiederholungsprüfung angegeben sind. Im Einzelfall keine eine Wiederholungsprüfung von der vorherigen Prüfung stärker abweichen. Es gelten immer die Regeln, die dis Dozenti bei der jeweiligen Wiederholungsprüfung veröffentlicht hat.
4. In der Regel werden alle weiteren *Hinweise* (wie z.B. die Themenvergabe) im *gleichen* *Moodlekurs* veröffentlich, in dessen Rahmen auch die ursprüngliche Prüfung ablief.
2.  Wird ein *Modul im laufenden Semester* angeboten, so gibt es keine Wiederholungsprüfung. Stattdessen können Sie ggf. an der regulären Klausur des Moduls teilnehmen. Es gilt der aktuelle Stoff bzw. die aktuellen formalen Bedingungen. Es ist möglich, dass der Stoff sich dann substanziell ändert; meist halten sich die Änderungen (im Stoff) aber in Rahmen.
5. Bitte beachten Sie, dass die meisten *Module nur ein Mal pro Jahr angeboten* werden (also entweder im Sommer- oder im Wintersemester, aber nicht beides. Eine Ausnahme ist das Bachelormodul, das jedes Semester angeboten wird).
3. Wird ein Modul im laufenden Semester nicht angeboten, gibt es eine *Wiederholungsprüfung*. 
2.  Sprechen Sie die *Moduldozentis an für Details zur Prüfung* (bzw. lesen Sie vorab auf jeweiligen Modulseite in Moodle nach).
2.  Manchmal fragen Studentis nach einer *Empfehlung*, ob es besser ist, eine Prüfung zu verschieben, wenn man sich nicht ausreichend vorbereiten konnte. Es ist schwer, eine Empfehlung pauschal abzugeben; es kommt auf den Einzelfall an. Grundsätzlich rate ich aber dazu, *Prüfungen nicht zu verschieben*: Schließlich könnte in einem folgenden Semester wieder ein unvorhergesehenes Problem auftreten. Und was man erledigt hat, hat man erledigt :-)
2.  Bei Fragen zum *Prüfungsrecht* sprechen Sie bitte die *Studienberatung* an.
3. Handelt es sich bei der Prüfung um eine Projektarbeit (oder vergleichbare Leistung), so ist als Wiederholungsprüfung ein *neues Thema* zu bearbeiten. Das "alte" (nicht eingereichte) Thema darf *nicht* weitergeführt werden, da sonst die Bearbeitungszeit unzulässigerweise zu lange wäre (z.B. ein Jahr).









##  Organisatorische Hinweise


### Allgemeines

1.  Etwaige weitere *Stoffeingrenzungen* werden schriftlich bekannt gemacht (auf der Modulseite). Besondere Schwerpunkte gibt es nicht.
2.  Soweit bestimmte Inhalte nicht explizit ausgeschlossen sind, sind alle Inhalte, die im Rahmen des Moduls bearbeitet wurden, *prüfungsrelevant.*
2.  Im Übrigen gelten die Hinweise der *offiziellen Regularien* wie SPO, auf dem Modulsteckbrief und der APO. Bitte kontaktieren Sie die Studienberatung für formale oder rechtliche Fragen. 
2.  Während der Prüfung werden nur Fragen beantwortet, die für die Bearbeitung zwingend nötig sind (etwa bei technischen Problemen).
2.  *Keine Vorab-Korrektur*: Es werden keine Fragen der Art "Ist diese Aufgabe klar formuliert?" beantwortet während der Prüfung. Sollten Sie der Meinung sein, eine Frage ist unklar formuliert oder fehlerhaft, so notieren Sie dies bitte (z.B. im Kommentarfeld der Prüfung). Der Prüfer untersucht im Nachgang die Angelegenheit. Stellt sich eine Frage als fehlerhaft oder unklar formuliert heraus, so wird sie von der Beurteilung herausgenommen.
2.  Eine Teilnahme an der Prüfung ist nur möglich, wenn Sie den *Teilnahmebedingungen* der Prüfung zustimmen. Nehmen Sie an der Prüfung teil, so heißt das, dass Sie die Teilnahmebedingungen akzeptiert haben. Falls Sie Fragen oder Hinweise haben, können Sie sich jederzeit an die Prüfperson wenden.
2.  Die *Aufgabenstellung* der Prüfung wird ggf. nur *während des Prüfungszeitraumes* angezeigt.
2.  Beachten Sie eine etwaige *Gruppeneinteilung* (zu welcher Gruppe Sie zugeteilt sind). 
2.  Beachten Sie die exakte *Prüfungsuhrzeit* (Beginn, Ende). 
2.  Prüfungszeitraum, Aufgabenstellung und sonstige Materialien können variieren zwischen den Prüflingen etwa aufgrund von *Gruppeneinteilungen* oder *Nachteilsausgleich.*
2.  Die zusätzliche Bearbeitungszeit bei Studentis mit *Nachteilsausgleich* ist in der Aufgabenstellung bzw. der Prüfung in Moodle hinterlegt. Die Zeit wird automatisch um den jeweiligen Faktor bzw. Wert erhöht.
3. Falls bei einer Prüfungsaufgabe keine Hinweise angegeben sind, *gelten* die *allgemeinen Hinweise des Hinweisbuch*, also diese Seite und andere relevante des Hinweisbuches. Falls Hinweise bei einer bestimmten Prüfung oder auch einer bestimmten Aufgabe angegeben sind, haben die Hinweise bei der Aufgabe Vorrang, ansonsten haben die Hinweise der Prüfung Vorrang vor den Hinweisen im Hinweisbuch.





### Technische Probleme während der Prüfung

Im Falle eines technischen Problems auf Seiten der *Prüfungsinfrastruktur* ist sofort der Prüfer zu informieren. 
Ein Beispiel für so ein Problem wäre etwa der Ausfall von Moodle. 
Der technische Fehler ist *nachvollziehbar* zu dokumentieren (z.B. Screenshot) und die Dokumentation ist sofort nach der Prüfung einzureichen. 
Bitte beachten Sie, dass der Prüfer bzw. die Hochschule *keine Gewähr* übernimmt für Probleme mit Ihrer eigenen (IT-)Ausstattung. 



### Zeitrahmen der Prüfung

Die Prüfung beginnt und endet zu einem festen Zeitpunkt. Sie sind selber verantwortlich, die Prüfung zur korrekten Zeit zu beginnen und zu beenden (einzureichen). 
Verspätete Abgaben werden u.U. als nicht bestanden gewertet. 
Die Dauer der Prüfung wird Ihnen von Ihrer Prüferin bzw. Ihrem Prüfer bekannt gegeben.




### Reihenfolge

Bei mündlichen Prüfungen: In der Regel präsentieren mehrere Studierende, so dass sich die Frage nach der Reihenfolge der Prüfungen stellt.
Aus Gründen der Fairness und Einfachheit bestimmt der Dozent die Reihenfolge  *zufällig*.

:::callout-note
Die Zufallsreihenfolge aller angemeldeten Prüflinge bestimmt der Dozent durch die R-Funktion `sample`, 
wobei als Startwert das Datum des (ersten) Prüfungstags herangezogen wird^[Im Format ISO 8601, z.B. "20240116"]. 
Beispiel: `$set.seed(20260120); sample(1:20)`, wenn die Prüfung am 20.01.2026 stattfindet und es 20 Prüflinge sind. 
Die alphabetische Folge (der Nachnamen) wird dann entsprechend deterministisch permutiert. \square$
:::

Den Studierenden steht es frei, ihre Position untereinander zu tauschen, sofern die Beteiligten alle zustimmen. 

















## Anspruch

In die Notengebung fließt folgende Konzeption zum Anspruch an die Prüfungsarbeit ein:


1. *Sehr gute Leistung*: Der Stoff aus dem Unterricht wird in sehr breitem Umfang und sehr hoher Tiefe in höchstem Maße korrekt angewandt. Die Stärken und Schwächen des gewählten Vorgehens werden ausgiebig und korrekt reflektiert.

2. *Ausreichende Leistung*: Wesentliche Teile des Stoffes aus dem Unterricht werden in einiger Breite wenn auch mit geringer Tiefe überwiegend korrekt angewandt. Eine Reflektion des Vorgehens ist in Ansätzen zu erkennen.


Es wird *kein unbehandelter Stoff* vorausgesetzt für (sehr gutes) Absolvieren der Prüfung.
Als "behandelter" Stoff gelten alle Inhalte, die als *prüfungsrelevant* gekennzeichnet sind.


## Keine Vorab-Korrektur

Aus Gründen der Gleichberechtigung wäre es nicht zulässig, einzelnen Studis die Frage "Können Sie mal über meine Arbeit drüber schauen, ob alles passt?" zu beantworten. Außerdem wäre es nicht sinnvoll: Dann würde der Prüfer ja sich selbst bewerten. Nicht die Prüfer haben ja eine Aufgabe zum Lösen gestellt bekommen,sondern die Studierenden haben eine Aufgabe zu lösen.
Wie aber unterstützen dann die Lehrkräfte bei einer Prüfung? Die Lehrkräfte haben die Verantwortung, den Studierenden alles an die Hand zu geben, um die Prüfungsaufgaben lösen zu können. Das beinhaltet auch, für *fachliche* Fragen bereitzustehen, aber nicht für Fragen wie "können Sie mir meine Prüfung vorab korrigieren?".





## Plagiate 





### Don't do it

Lassen Sie äußerste Vorsicht walten, dass sich *keine Plagiate* in Ihrer Abschlussarbeit finden. 
Finde ich ein oder mehrere Plagiate, so werde ich die Arbeit mit "nicht bestanden" beurteilen. 
Eine Leistung als die eigene auszugeben, 
die aber gar nicht die eigene ist, ist Betrug. 
Bitte bedenken Sie auch, dass eine Ausrede wie "war keine Absicht, hab nicht aufgepasst" nicht ausreicht: 
*Sie* sind für die Qualität und Redlichkeit Ihrer Arbeit verantwortlich. 
In Ihrer Verantwortung liegt entsprechend die notwendige Sorgfalt, Plagiate zu vermeiden.
Auch die Ausrede "Mein Literaturprogramm oder Word muss hier einen Fehler gemacht haben" wird nicht gelten gelassen werden. 
Hier gilt wieder: Sie sind für die Qualität und Redlichkeit Ihrer Abschlussarbeit verantwortlich;
die Verantwortung ist nicht an eine Maschine delegierbar. 
Falls Sie Fragen zu dem Thema Plagiate haben, sprechen Sie mich jederzeit gerne an.



Ihre Prüfungsarbeiten können auf Plagiate hin untersucht werden, auch unter Einsatz von maschinellen Methoden oder KI-basierten Methoden (z.B. mit [dieser Methode](https://pubmed.ncbi.nlm.nih.gov/37426542/)). 
Dabei können die Daten auch an Drittanbieter (z.B. Anbieter von Software zur Plagiatserkennung).

Bitte beachten: Angenommen in den Projektarbeiten von Studenti A und B werden (substanzielle) Überlappungen gefunden. 
In dem Fall ist davon auszugehen, dass *beide* Studentis getäuscht haben: eine/r hat abgeschrieben, der/die andere hat die eigene Arbeit dafür bereitgestellt. 
Daher wird in diesem Fall u.U.  bei beiden Studentis der Plagiatsfall festgestellt und geahndet (z.B. mit "nicht  bestanden" bewertet). 
Die genauen Konsequenzen legt die Prüfungskommission im Einzelfall fest.

Lassen Sie es auf keinen Fall soweit kommen: 
Schreiben Sie nicht ab und lassen Sie niemanden von Ihrer Arbeit abschreiben. 

Eine faire Prüfung heißt: *Gleiche Chancen für alle*, und *gute Leistung wird belohnt*, Täuschung nicht.






### ... und zu unerlaubten Hilfsmitteln

Zu unerlaubten Hilfsmitteln zählt insbesondere die Hilfe Dritter. 
Die Arbeit darf nur mit Hilfe erlaubter Hilfsmittel geschrieben werden. 
So ist es nicht zulässig, dass Teile Ihrer Arbeit von anderen Personen geschrieben, verbessert oder sonstig beeinflusst werden. 
Zu solchen unerlaubten Hilfsmitteln zählt auch das "Korrekturlesen" durch Dritte. 
Bei Fragen oder im Zweifel sprechen Sie bitte Ihre Betreuerin/Ihren Betreuer an. Das Verwenden von unerlaubten Hilfsmitteln kann von der Prüfungskommission mit Nichtbestehen der Prüfung geahndet werden.
Erkundigen Sie sich im Zweifelsfall beim Ihrem Prüfer zu den erlaubten bzw. nicht
erlaubten Hilfsmitteln der Prüfung.





## Korrekturhinweise




### Typische Fehler in der Prüfung

1.  *Rechtschreibfehler* Manchmal muss man genau hinschauen, und leicht vertippt man sich: So heißt der Datensatz vielleicht `tips` und die Spalte, um die es Ihnen geht `tip` (oder war es umgekehrt?). Oder die Spalte heißt `bill_length` aber Sie schreiben `bill_lenght`.
2.  *Datensatz nicht richtig importiert* Ob ein Datensatz richtig importiert ist, erkennen Sie daran, ob er im Reiter "Environment" angezeigt wird. Außerdem können Sie dort den Datensatz anklicken, um zu einer Tabellenansicht des Datensatzes zu gelangen. Dort können Sie erkennen, ob z.B. die Anzahl der Spalten korrekt ist (und nicht etwa nur eine) oder z.B. ob die Spaltennamen korrekt sind.
2.  *`data(datensatz)` ohne vorher das zugehörige R-Paket gestartet zu haben*: Mit `data(datensatz)` können Sie den Datensatz `datensatz` *nur* dann verfügbar machen, wenn das Paket, in dem `datensatz` "wohnt", mit `library(paketname)` gestartet worden ist. So "wohnt" z.B. `penguins` im Datensatz `palmerpenguins`. [Hier](https://datenwerk.netlify.app/post/pfad/pfad/) finden Sie eine Übung (und weitere Erklärung) zum Importieren von Daten in R am Beispiel des Datensatzes `penguins`.
2.  Verwenden einer *Funktion, ohne das zugehörige R-Paket* vorab gestartet zu haben.
2.  Das Laden *zu vieler R-Pakete*, die gar nicht benötigt werden, mit dem Ergebnis, dass es mehrere Funktionen des gleichen Namens gibt (z.B. `filter()`). Das führt dann zu Verwirrung, da dann z.B. nicht die Funktion `filter` aus `tidyverse` (`dplyr`) verwendet wird, wie Sie annehmen, sondern eine Funktion gleichen Namens aus einem anderen Paket, das Sie auch gestartet haben. Tipp: Starten Sie nur die Pakete, die Sie für die Aufgabe benötigen. Zumeist sind das immer die gleichen wenigen Pakete.





### Hinweise zu Scheinmängeln

Immer wieder kommt es vor, dass Studierende Beanstandungen zu einer Prüfung vorbringen. Teilweise sind diese gerechtfertigt, teilweise nicht. Im Folgenden sehen Sie eine Auswahl an *nicht* gerechtfertigten Beanstandungen, also nur scheinbaren Mängeln, keine wirklichen Mängel, in einer Prüfung.

-   "*Das zu wählende Vorgehen war nicht 100% klar*" -- Wenn Sie der Meinung sind, dass das zu wählende Vorgehen (zum Lösen der Aufgabe) nicht komplett klar ist, treffen Sie Annahmen und weisen Sie darauf hin, dass Sie Annahmen getroffen haben. Zum anderen halten Sie sich an das Vorgehen aus dem Unterricht (bzw. den Unterlagen und der Literatur, die im Unterricht verwendet wurde). Eine andere Situation läge vor, wenn die Aufgabe nicht lösbar ist ohne weitere Angaben lösbar ist("Ist ein Effekt bei n=100 signifikant?"). Im Falle einer nicht lösbaren Aufgabe liegt der Fehler beim Prüfer.

-   "*Ich sollte einen Punkt (ein Komma) als Dezimaltrennzeichen verwenden, aber Moodle hat ein Komma (einen Punkt) verlangt!*" -- Je nach Spracheinstellung in Moodle kann es sein, dass Moodle nur einen Punkt als Dezimaltrennzeichen bzw. ein Komma als Dezimaltrennzeichen verwendet. Moodle weist Sie aber darauf hin, wenn eine Zahl nicht als Zahl erkannt wird, und zwar wenn Sie zur nächsten Aufgabe geben. Sie können also ohne Probleme den Fehler korrigieren. Darüber hinaus ist bei den Prüfungshinweisen vorab auf diesen Punkt verwiesen.

-  "*Ich sollte die Lösung als Anteil angeben, habe sie aber in Prozent angeben, also `42%` anstatt von `0.42`*". -- Da die angegebene Lösung (als Prozentzahl) falsch ist, kann sie nicht als richtig gewertet werden.



### Prüfungseinsicht

Sie haben das Recht, Ihre Prüfungsergebnisse einzusehen  innerhalb der gesetzlich geregelten Fristen.
Der Termin zur Einsichtnahme in die Prüfungsergebnisse wird von mir rechtzeitig (innerhalb der Frist) bereit gestellt (online).
Beachten Sie bitte, dass für bestimmte Prüfungsformate keine Einsicht möglich ist bzw. die Einsicht schon vorab veröffentlicht sein kann:

- Bei Projekt- oder Abschlussarbeiten stelle ich ggf. ein Gutachten schon vorab bereit (z.B. via Moodle). Ich schreibe *nichts* in Ihre Projektarbeit. Außerhalb des Gutachtens gibt es (bei mir) nichts einzusehen.
- Bei Prognosewettbewerben gründet sich die Note primär oder komplett auf die Vorhersagegüte. In aller Regel gibt es keine weiteren Korrekturen oder Hinweise zur Analyse. Daher gibt es keine Einsichtnahme für diese Prüfungsform.

Die Prüfungseinsicht findet zu Beginn
des Folgesemesters statt. Der Termin wird auf der Moodle-Seite,
auf der auch die Prüfungsaufgaben stehen, bekannt gegeben.

Zur Prüfungseinsicht öffnen Sie bitte Ihre Aufgabenstellung in Moodle.
Die Musterlösung sowie Ihre Antwort inkl. Bewertung (richtig/falsch) wird dann angezeigt.


Bitte beachten Sie bei der Einsichtnahme:

1. Die Einsichtnahme findet individuell und online statt.
2. Der Prüfer ist nicht anwesend.
3. Falls Sie der Meinung sind, einen Fehler in einer Aufgabe oder der Korrektur gefunden zu haben, beachten Sie bitte die Hinweise unter @sec-beanstandung.





### Beanstandung der Note {#sec-beanstandung}


Falls Sie der Meinung sind, der Gutachter hätte Ihre Arbeit nicht korrekt beurteilt, 
haben Sie folgende Möglichkeiten zur Beanstandung der Note.
Bitte halten Sie folgende Reihenfolge ein:



1. *Prüfungseinsicht*: Schauen Sie sich die Aufgabe und Bewertung genau an. 
2. *Formale Hinweise*: Lesen Sie sich die formalen Hinweise zur Prüfung, ihren Anforderungen und typischen Fehlern genau durch, um zu sehen, ob Ihr Kritikpunkt nicht vielleicht in den Hinweisen zur Prüfung schon aufgegriffen wird.
2. *Gespräch* mit *Gutachter*: Sprechen Sie mit der Lehrkraft, versichern Sie zunächst, dass Sie alle Hinwiese gelesen haben. Vielleicht kann man in einem Gespräch etwaige Missverständnisse klären.
3. *Formal Widerspruch einlegen*: Sie können formlos beim Studierendenservice Widerspruch einlegen (nur bis 4 Wochen nach Notenbekanntgabe). Ihr Widerspruch wird dann in der Fakultät geprüft. Der Studierendenservice lässt sich die Unterlagen des Prüfers geben und leitet den Widerspruch und die Prüfung an den Prüfungsausschuss weiter. Dieser entscheidet über die Note. Nur im Zweifelsfall kommt hier noch der Zweitprüfer ins Spiel.
4. Prüfen Sie ggf. rechtliche Schritte.


Folgenden Kritikpunkte von Studentis führen i.d.R. *nicht* zu einer Änderung der Note:

- "Das ist zu *streng* benotet."
- "Da war *kein konstruktives* Feedback dabei."
- "Der Gutachter hat nicht geschrieben, wie man den Satz/das Argument/die Seminararbeit *besser formuliert* hätte."
- "Die *Note passt nicht zu den Hinweisen* der Gutachterin."
- "Der Gutachter *konnte mir die Note nicht verständlich* machen."
- "Eine *andere Studentin* hat das aber so ähnlich geschrieben wie ich, und ihre Arbeit wurde *besser benotet*" - die Vergleichbarkeit von Seminararbeiten ist komplex, die Gesamtnote setzt sich aus vielen Aspekten zusammen, so dass man anhand eines einzelnen Aspekts nicht die Vergleichbarkeit der Noten beurteilen kann.
- "Die Aufgaben waren zu *schwierig.*"
- "Ich bin mit der Note *nicht zufrieden*. Ich hätte mir was Besseres erhofft."
- "Ich habe *nichts aus dem Gutachten gelernt*."
- "Da war *kaum Negatives* im Gutachten."
- "Ich hätte mir *mehr Unterstützung* von Ihnen gewünscht."



Folgenden Kritikpunkte von Studentis haben *Aussicht* auf eine *Änderung* der Note:

- Der Gutachter hat sich *verzählt* (oder Punkte übersehen): Sie haben tatsächlich 43 Punkte, aber er hat nur 42 Punkte gezählt.
- Die Gutachterin hat einen Teil der *Prüfungsleistung übersehen* (vielleicht war ein Teil des Textes in einem Anhang, der in einer separaten Datei beigefügt war, die die Gutachterin nicht gesehen hat).
- Die Aufgabenstellung war *falsch* ("Was ist der Logarithmus von -1?").
- Die Aufgabenstellung war *missverständlich* ("Erläutern Sie den Hintergrund: 'Islamistische Selbstmordattentäter wollen als Mehrtürer sterben.'")






### Bitte formulieren Sie Beanstandungen nachvollziehbar

Falls Sie einen Fehler in einer Aufgabenstellung finden (die der Prüfer zu bestanden hat): Freuen Sie sich! In diesem Fall wird zu Ihren Gunsten entschieden.

Damit ich Ihre Beanstandung prüfen kann, ist es nötig, dass ich Ihre *Beanstandung* nachprüfen kann: *Zeigen* Sie mir meinen Fehler. 
Es reicht *nicht* zu sagen "es hat bei mir nicht funktioniert". 
Wenn Sie etwa der Meinung sind, dass es die Variable "year" im Datensatz "penguins" nicht gebe, dann schicken Sie mir den R-Code,
der an ansprechender Stelle einen Fehler aufwirft (aber *ansonsten lauffähig* ist). 
Ein Screenshot kann in einigen Situationen helfen,
wenn aber nur ein Teil der Syntax zu sehen ist, ist er nicht ausreichend: Wenn der Befehl `data(penguins)` nicht funktioniert, 
so ist zu prüfen, ob Sie vorab mit `library(palmerpenguins)` das relevante Paket gestartet haben. 
Andernfalls kann `data(penguins)` nicht funktionieren und der Fehler läge damit bei Ihnen.

[Hier](https://data-se.netlify.app/2022/01/31/erbie-einfache-reproduzierbare-beispiele-ihres-problems-mit-r-syntax/) finden Sie Hinweise für *e*infache, *r*eproduzierbare *Bei*spiele (ERBies); vgl. Sauer (2019), Kap. 3.8.2 (S. 33).



Die gleiche Messlatte lege ich an mich an: Ich stelle eine Musterlösung (bei der Einsichtnahme) zur Verfügung, die reproduzierbar die Lösung aufzeigt. Sprich: Wenn der R-Code bei mir durchläuft, so wird er auch bei Ihnen durchlaufen.




## Tipps

- Legen Sie regelmäßig *Sicherheitskopien* Ihrer Projektarbeit an (ggf. auf einem anderen Datenträger).
- Achten Sie darauf, dass Sie *nicht mit den Versionen durcheinander* kommen, in welcher Datei der aktuelle Stand Ihrer Projektarbeit liegt.
- Lesen Sie die *Hinweise* sorgfältig durch, v.a. solche zu Prüfungsbedingungen.
- Teilen Sie sich die *Zeit* entsprechend ein.



