---
title: "Untitled"
format: html
---

# Als Tutor arbeiten

## Organisatorisches

Sie haben ein Modul erfolgreich abgeschlossen und möchten nun als Tutor oder Tutorin arbeiten?
Sehr gut! 
Eine Tutorenstelle ist eine tolle Möglichkeit, um Ihr Wissen zu vertiefen und gleichzeitig wertvolle Erfahrungen zu sammeln.
Das Beste ist, dass Sie anderen Studierenden helfen, den Stoff zu verstehen und ihre Fähigkeiten zu verbessern.
Sie engagieren sich für eine gute Sache und unterstützen Ihre Kommilitoninnen und Kommilitonen auf ihrem akademischen Weg.

### Ihr Nutzen

- Zertifikat des begleitenden Professors, dass Sie als Tutor gearbeitet haben
- Vertiefung des eigenen Wissens
- Entwicklung von pädagogischen Fähigkeiten
- Ansprechende Vergütung

### Voraussetzungen
- Erfolgreicher Abschluss des Moduls, für das Sie als Tutor arbeiten möchten
- Interesse daran, anderen Studierenden zu helfen und sie zu unterstützen
- Gute Kommunikationsfähigkeiten und grundlegende didaktische Fähigkeiten
- Bereitschaft, selber zu lernen und sich weiterzuentwickeln


### Bewerbung
- Bitte setzen Sie mich mit dem jeweiligen Professor in Verbindung, der das Modul leitet.
- Bitte beachten Sie, dass die Anzahl der Tutorenstellen begrenzt ist und die Vergabe nach bestimmten Kriterien erfolgt.


## Aufbau des Tutoriums


- In der Regel findet ein Tutorium wöchentlich statt und dauert etwa 90 Minuten.
- Sie können das Tutorium entweder in Präsenz oder (auch) online abhalten, je nach den Bedürfnissen der Studierenden.
- Der Termin sollte so gelegt werden, dass möglichst viele Studierende teilnehmen können (keine Überschneidung mit Vorlesungen, etc.).
- Sie arbeiten selbständig; es gibt keine direkte Aufsicht durch den Professor.
- Es empfiehlt sich, einen Moodle-Kurs für das Tutorium anzulegen, um Materialien zu teilen und Ankündigungen zu machen.


## Inhalt

- Das Tutorium sollte sich auf die Inhalte der begleitenden Vorlesung konzentrieren.
- Sie können verschiedene Methoden verwenden, um den Stoff zu vermitteln, z.B. durch Diskussionen, Gruppenarbeiten, praktische Übungen oder Präsentationen.
- Es ist wichtig, dass Sie den Studierenden die Möglichkeit geben, Fragen zu stellen und Unklarheiten zu klären.
- Ein Schwerpunkte sollte auf der Bearbeitung von Übungsaufgaben liegen, um das Verständnis zu vertiefen. Nutzen Sie gerne die Aufgaben aus den Vorlesungen.
- Sie können auch eigene Materialien erstellen, um den Stoff zu veranschaulichen.


## Bei Fragen

Zögeren Sie nicht, mich zu kontaktieren, wenn Sie Fragen haben oder Unterstützung benötigen.
Ich wünsche gutes Gelingen und viel Erfolg bei Ihrer Tätigkeit als Tutor oder Tutorin!


