# Häufige Fehler in der Datenanalyse


## Schwere Fehler


Schwere Fehler, die zum Durchfallen oder deutlichem Abwerten der Note führen können, sind z.B.:

- fehlende Inferenzstatistik (oder adäquatem Ersatz)
- falsche Interpretation von Posteriori-Verteilungen oder p-Werten
- keine Angabe von Konfidenzintervallen 
- falsche Interpretation von Konfidenzintervallen
- Wahl des falschen Intervalls (Vorhersageintervall vs. Perzentilintervall vs. HDI)
- falsche Entscheidung zum Hypothesentest auf Basis entsprechender Kennwerte (wie ROPE-Wahrscheinlichkeit oder p-Wert) 
- falsche Wahl des statistischen Verfahrens 
- fehlende Deskriptivstatistik



## Leichte Fehler

Häufige kleinere Mängel sind z. B.

- pixelige Abbildungen 
- R-Ausgaben oder R-Syntax als Screenshot 
- fehlende Seitenzahlen (nur bei paginierten Formaten, nicht bei HTML) 
- unübersichtliche Diagramme 
- kein (verlinktes) Inhaltsverzeichnis ︎
- fehlende oder unverständliche Achsenbeschriftung bei Diagrammen 
- fehlende oder falsche Beschreibung der/des Skalenniveau(s) der untersuchten Variablen

