# Häufige Fehler in schriftlichen Prüfungen





## Überblick über typische Fehler

1. *Fachlich dünn*: Die Anzahl von guten Quellen (z. B. Fachartikel) ist gering; der Autor kennt sein Thema zu wenig. Es findet kaum Rückbezug der eigenen Studie/Daten auf die Literatur statt.

2. *Stoff nicht ausreichend reflektiert*: Es werden Fakten aneinander gereiht, ohne dass ist, ob sich mit dem Stoff auseinander gesetzt wurde (z. B. werden Stärken/Schwächen einzelner Texte nicht diskutiert).

3. *Formalia fehlerhaft*: Durch „Äußerlichkeiten“ werden Punkte verschenkt (z. B. pixelige Grafiken, optisch schlecht aufgelockerte Texte, „Löcher“ im Textfluss; Fehler im Literaturverzeichnis).

4. *Zahlen irreführend präsentiert*: Statistiken wie werden unvollständig präsentiert oder die Anzahl der Nachkommastellen ist zu hoch oder inkonsistent.

5.  *Selbstkritik fehlt*: Stärken und Schwächen der eigenen Art werden nicht diskutiert.


## Substanzielle Fehler

*Substanzielle* Fehler können zum *Durchfallen* oder zum deutlichem Abwerten der Note führen. Beispiele für solche Fehler sind:

- Die *Textlänge* (Hauptteil) ist zu *kurz* – ca. 20 % unter der formal angegeben Soll-Länge.
- Es liegen viele *Zitierfehler* im Text vor (z. B. 30 % fehlerbehaftete Zitationen).
- Es liegen viele *Fehler* im *Literaturverzeichnis* vor (z. B. 30 % fehlerbehaftete Zitationen).
- Es wurde die abgesprochene empirische *Methode nicht verwendet*.
- Das *Literaturverzeichnis* ist sehr *kurz* (weniger als 15 (Bachelor) bzw. 25 (Master) Quellen).
- Die *Qualität* des *Literaturverzeichnisses* ist gering (über 50 % Quellen von zweifelhafter Qualität, z. B. aus Ratgeber-Büchern).
- Die *Lesbarkeit* ist aufgrund der optischen Gestaltung oder gravierender *Sprachmängel* stark eingeschränkt (z. B. viele Rechtschreibfehler).
- Es findet sich ein oder mehrere *Plagiate* (weitere Konsequenzen sind möglich).


### In quantitativen Arbeiten

- Es wird *keine Inferenzstatistik* verwendet.
- Der *p-Wert* oder die *Post-Verteilung *(und ihre Derivate) werden falsch interpretiert.
- Es wird *keine Deskriptiv-Statistik* berichtet.
- *Hypothesen* und *Datenanalyse* *passen nicht zusammen*.
- Die *Stichprobe* ist *kleiner* als 50% der Menge, die für die Teilnote "gut" ausgewiesen ist.

### In qualitativen Arbeiten

- Es werden *keine Kategorien *berichtet.
- Es werden nur *wenig Kodierungen* vorgenommen.
- Es werden *keine Kodierregeln* berichtet.
- Die *Stichprobe* ist *kleiner* als 50% der Menge, die für die Teilnote "gut" ausgewiesen ist.

### In theoretischen Arbeiten

- Es wurde ein *stark verzerrtes Bild* der einschlägigen Literatur berichtet.
- Die Menge der verwendeten Literatur ist weniger als 50% der Menge, die für die Teilnote "gut" ausgewiesen ist.


