project:
  type: book
  
  
lang: de
citation: true
#google-scholar: true
description: |
  "Hinweise zu Pr체fungen und Lehre bei Prof. Sebastian Sauer"
license: "MIT" 

  

book:
  title: "Hinweise"
  author: Sebastian Sauer
    # - name: Sebastian Sauer
    #   orcid: 0000-0003-1515-8348
  image: img/hinweise-logo.png
  description: "Hinweise zu Pr체fungen und Lehre bei Prof. Sebastian Sauer"
  date: now
  reader-mode: true
  page-footer:
    border: true
    left: |
      Powered by [Quarto](https://quarto.org)
    center: |
      [Impressum](https://sebastiansauer.github.io/hinweisbuch/impressum.html)
    right: |
      [Datenschutzhinweise](https://sebastiansauer.github.io/hinweisbuch/datenschutz.html)
  
  sidebar: 
    logo: img/hinweise-logo.png
  favicon: img/hinweise-logo.png
  repo-url: https://github.com/sebastiansauer/hinweise
  repo-actions: [issue] 
  
  chapters:
    - index.qmd
    - part: "Pr체fungen"
      chapters:
      - 010-Hinweise-Pruefung-allgemein-frame.qmd
      - 020-Hinweise-Pruefung-Open-Book-frame.qmd
      - 030-Hinweise-Pruefung-Klausur-frame.qmd
      - 040-Hinweise-Pruefung-Datenanalyse-frame.qmd
      - 045-Hinweise-Pruefung-Fachgespraech-frame.qmd
      - 050-Hinweise-Pruefung-Praesentation-frame.qmd
      - 060-Hinweise-Pruefung-Projektarbeit-frame.qmd
      - 070-Hinweise-Pruefung-Gruppenarbeit-frame.qmd
      - 080-Hinweise-Pruefung-Prognosewettbewerb-frame.qmd
      - 090-Hinweise-Pruefung-Poster-frame.qmd
      - 100-Hinweise-Pruefung-Thesis-frame.qmd
      - 105-Hinweise-Pruefung-Review-frame.qmd
      - 108-Hinweise-Quali-frame.qmd
    - part: "Unterricht"
      chapters:
        - 110-Hinweise-Didaktik-frame.qmd
        - 120-Hinweise-Unterricht-frame.qmd
        - 130-hinweise-software.qmd
        - 140-boni.qmd
    - part: "Lernen"
      chapters: 
        - 150-Hinweise-Pruefungsvorbereitung-frame.qmd
        - 160-Hinweise-Lernhilfen-frame.qmd
        - 165-Hinweise-Thesis-frame.qmd
    - part: "H채ufige Fehler"
      chapters: 
        - 170-Beispiele-Fehler-Prognosewettbewerb-frame.qmd
        - 180-Beispiele-Fehler-Datenanalyse-frame.qmd
        - 190-Beispiele-Fehler-Projektarbeiten-frame.qmd
    - part: Rechtliches
      chapters:
        - impressum.qmd
        - datenschutz.qmd        

bibliography: bib/bib.bib

format:
  html:
    toc: true
    theme:
      light: [united, mytheme.scss] 
      dark: solar
    # theme: 
    #     - united
    #     - custom.scss
    number-sections: true
    df-print: paged
    code-fold: false
    fig-align: center
    code-link: true
    author-meta: "Sebastian Sauer"
    mermaid:
      theme: neutral



