



## Didaktische Ziele der Gruppenarbeit als Prüfungsform



Bei einer *Gruppenarbeit* wird ein Projekt, etwa eine empirische Studie, ein Praxisprojekt oder eine Datenanalyse, von mehreren Personen bearbeitet.

Neben der inhaltlich-methodischen Kompetenz soll im Rahmen dieser Prüfungsform abgeprüft werden, 
ob und wieweit sich die Studierenden mit den *sozialdynamischen Prozessen* erfolgreich auseinander setzen können. 
Dies ist vor dem Hintergrund der Allgegenwärtigkeit von Arbeitsgruppen im Berufsleben begründet. 
Für die berufliche Ausbildung ist es wichtig, *Erfahrung mit den Vorzügen aber Schwierigkeiten von Arbeitsgruppen*  gemacht zu haben.
Eine Prüfungsleistung an der Hochschule bietet dafür einen geschützten Rahmen.



## Arbeitsteilung der Gruppenmitglieder

Die Aufteilung der Teilaspekte der Arbeit soll so erfolgen, dass jedes Mitglied des Teams *ein komplettes empirischen Kapitel* (Methodenteil oder Ergebnisteil) und *ein komplettes theoretischen Kapitel* (Theorieteil oder Diskussion) verfasst. 
Zu dem der *Hauptkapitel* des Berichts (z.B. Theorie, Methode, Ergebnis, Diskussion) ist genau ein Name anzugeben, die für das entsprechende Kapitel verantwortlich ist.
Geben Sie den Namen in geeigneter Form an, z.B. in einer Fußnote zu der Kapitelüberschrift.
Eine Aufteilung der Hauptkapitel auf mehrere Personen eines Teams ist nicht zulässig.

Die *Einleitung* soll *gemeinsam*  verfasst werden.





## Benotung


1. *Einzelnote*: Jedes Mitglieder einer Arbeitsgruppe erhält eine eigene, individuelle Note. Die Noten der Gruppenglieder müssen daher nicht identisch sein (können aber). Alle Kommentare des Gutachters sind mit dem Namen (bzw. Namenskürzel) derjenigen Person versehen, an die der Kommentar gerichtet ist. In die Note (eines bestimmten Gutachtens) fließen nur Abschnitt ein, die von der/dem angegebenen Verfasser:in verfasst wurden sowie diejenigen Abschnitte, die nicht namentlich gekennzeichnet wurden (nur relevant bei Gruppenarbeiten). Kommentare zu Abschnitten, die ohne Namen in der Prüfungsleistung angegeben sind, werden auch ohne Namenshinweis aufgeführt.

2. Beachten Sie, dass die *Noten der Prüflinge einer Gruppe identisch sein können* (aber nicht müssen).
Beachten Sie auch, dass es Aspekte eines Projekts gibt, die auf die Arbeitsteile mehrerer Gruppenmitglieder Auswirkung haben. Beispiel: Die theoretische Grundlage einer Forschungsfrage hat Auswirkung auf das zu wählende Forschungsdesign, was wiederum auf die Auswertungsmethodik auswirkt. Schließlich ist die Diskussion der Schwächen der Studien abhängig von den anderen Teilen bzw. dem Vorgehen im Projekt.



## Formalia


1. Wenn eine Gruppenarbeit als Prüfungsform definiert ist sind *Einzelarbeiten grundsätzlich nicht zulässig*. Umgekehrt sind Gruppenarbeiten (grundsätzlich) nicht zugelassen, wenn die Prüfungsform als Einzelarbeit definiert ist.


2. Die *Anzahl der teilnehmenden Personen* (min., max.) einer Arbeitsgruppe wird von der Prüfperson bekanntgegeben (z.B. min:2, max:4).

<!-- 3. *Abschnittsverantwortliche*: Jedes Kapitel  muss mit genau einem Namen ausgewiesen sein. Der Namen der/des Autor*in soll als Fußnote an die jeweilige Überschrift angefügt sein. -->

5. Aus formalen Gründen darf die Seminararbeit *pro Arbeitsgruppe* nur *einmalig* eingereicht werden. Im Falle mehrerer Einreichungen zählt die erste.

11. *Gleichwertige Beiträge*: Alle teilnehmenden Personen einer Forschungsgruppe (einer Gruppenarbeit) sollen in ähnlichem Umfang beitragen.

13. Es ist erlaubt, eine *Gruppe zu verlassen*. Wer eine Gruppe verlässt, schließt sich rechtzeitig einer anderen Gruppe an.

14. *Konflikte in der Gruppe*: Unterschiedliche Ansichten zum Vorgehen sind zuerst innerhalb der Gruppe zu klären. Falls dies erfolglos ist, soll (wenn nötig) die Lehrperson angesprochen werden. Zu beachten ist, dass das Moderieren des Gruppenprozesses Teil der Prüfungsleistung ist. 

15. Falls ei *Studenti keine Partner* bzw. keine Arbeitsgruppe findet nach selbständigen Suchen, ist bitte die Lehrkraft zu kontaktieren.

